### Getting differential operators

In [1]:
import torch
import torch.nn as nn
from torch.autograd import grad
import torch.nn.functional as F

In [2]:
x = torch.ones(2, 2, requires_grad=True)
v = x + 2
y = v ** 2

dy_dx = grad(outputs=y, inputs=x, grad_outputs=torch.ones_like(y))
print(f'dy/dx:\n {dy_dx}')

dv_dx = grad(outputs=v, inputs=x, grad_outputs=torch.ones_like(v))
print(f'dv/dx:\n {dv_dx}')

dy/dx:
 (tensor([[6., 6.],
        [6., 6.]]),)
dv/dx:
 (tensor([[1., 1.],
        [1., 1.]]),)


In [3]:
class MyFunction(nn.Module):
    def __init__(self,input_size=2,output_size=1):
        super(MyFunction, self).__init__()
        self.linear1 = nn.Linear(input_size,5)
        self.linear2 = nn.Linear(5,5)
        self.linear3 = nn.Linear(5,output_size)

    def forward(self,x):
        z = torch.sigmoid(self.linear1(x))
        z = torch.sigmoid(self.linear2(z))
        z = torch.sigmoid(self.linear3(z))
        return z

In [4]:
func = MyFunction()
x = torch.rand(2, requires_grad=True)
z = func(x)

dz_dx = grad(outputs=z, inputs=x, grad_outputs=torch.ones_like(z))
print(f'dy/dx:\n {dz_dx}')

dy/dx:
 (tensor([-0.0012,  0.0027]),)
